### ISSUE TITLE
404 node-usb

### ISSUE THREAD

**Issue by MegaGio94** [hannseman/homebridge-mi-hygrothermograph#105]
### Expected Behavior

It should install without errors

### Current Behavior

I get "prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v72-linuxmusl-arm.tar.gz" and I think because of that i get no readings from my bluetooth xiaomi device

### Steps to Reproduce (for bugs)

I managed to get homebridge-mi-hygrothermograph working on a homebridge docker container before the v3.0 update, when i upgraded to version 3.0 during the installation i have this strange error, it seems that link does not exists. I tried to rebuild from zero the docker image installing only homebridge-mi-hygrothermograph and I have this kind of error, even from the browser it gives me 404. After all the compilation I have an infinite series of errors.
<img width="1115" alt="Schermata 2020-05-18 alle 17 15 44" src="https://user-images.githubusercontent.com/26750152/82234173-5b27be80-9931-11ea-89bc-8e064d122dcd.png">

### Versions

- **homebridge**: `homebridge --version` 1.1.0
- **homebridge-mi-hygrothermograph**: `npm list --depth 1 --global homebridge-mi-hygrothermograph` 3.0.0
- **node**:       `node --version` 12.16.3
- **OS**:          Alpine Linux (3.11.6)

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by hannseman** [comment]
I just published a new version (`3.0.1`) which should install better. It installs fine for me on `docker run --rm -it node:12`. Please close this issue if it's resolved.

**Comment by MegaGio94** [comment]
I have the exact same compiling error during the installation, but now: "[Temperature & Humidity] Start scanning." So now i see the temperature and humidity according to my xiaomi device. Should i close the issue?
<img width="798" alt="Schermata 2020-05-24 alle 16 07 49" src="https://user-images.githubusercontent.com/26750152/82756198-f1982c00-9dd8-11ea-9181-ae21258c8252.png">

**Comment by hannseman** [comment]
👍
