### ISSUE TITLE
incompatible with webos-tv plugin

### ISSUE THREAD

**Issue by Hussamfhaily** [hannseman/homebridge-mi-hygrothermograph#108]
Hi, when I install this plugin it breaks the webos-tv plugin, and homebridge doesn't work anymore. I should uninstall the homebridge-mi-hygrothermograph plugin in order to make everything work again. Is it am matter of incompatibility? Thank you.

**Comment by hannseman** [comment]
Hi, it's very hard for me to troubleshoot this without any error messages. What can you see in the logs?

**Comment by hannseman** [comment]
Closing due to no response.
