### ISSUE TITLE
Problems with node 12.18.0 and npm 6.14.5

### ISSUE THREAD

**Issue by hecguillem** [hannseman/homebridge-mi-hygrothermograph#110]
Hello,

I am using homebridge last versión and node 12.18.0 and npm 6.4.15.

A lot of times sensor appears like " no response ",  I solve it restarting homebridge and Docker, and sometimes uninstalling plugin and installing again 

Also I use this command: sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)

Any solution to fix it?

Thanks for your work and time,

Héctor

**Comment by mich-bb** [comment]
“*/5 * * * * /usr/bin/timeout 50s /usr/bin/hcitool lescan” in crontab works nice for me.
But I hope there will a permanent decision.

**Comment by hecguillem** [comment]
Solved using this command.

crontab -e

0 * * * * sudo timeout -s INT 1s hcitool lescan

Thanks to @iShift !!

**Comment by hannseman** [comment]
Closing this issue due to a workaround is available and the issue seems to be firmware / bluetooth library related.
