### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by borez** [hannseman/homebridge-mi-hygrothermograph#117]
Hi there,

I upgraded my rPi4 installation to Ubuntu 20.04 64bit, and am having some problems installing the plugin. I had followed the instructions on the main page. Didn't have any issues when installing on raspbian.
In HB logs I get an error message as follows.

`[10/24/2020, 1:18:26 PM] Error: ENODEV, No such device
    at Hci.init (/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100:35)
    at NobleBindings.init (/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:78:13)
    at /usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/noble.js:60:24
    at processTicksAndRejections (internal/process/task_queues.js:79:11)`

Installation logs are as follows. Thank you so much!

`> usb@1.6.3 install /usr/lib/node_modules/homebridge-mi-hygrothermograph/node_mo                                                                                    dules/usb
> prebuild-install --verbose || node-gyp rebuild

prebuild-install info begin Prebuild-install version 5.3.6
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/186152                                                                                    -usb-v1.6.3-node-v72-linux-arm64.tar.gz
prebuild-install http request GET https://github.com/tessel/node-usb/releases/do                                                                                    wnload/v1.6.3/usb-v1.6.3-node-v72-linux-arm64.tar.gz
prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v                                                                                    1.6.3/usb-v1.6.3-node-v72-linux-arm64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=12.19.0 runtime                                                                                    =node arch=arm64 libc= platform=linux)
make: Entering directory '/usr/lib/node_modules/homebridge-mi-hygrothermograph/n                                                                                    ode_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
  AR(target) Release/obj.target/usb.a
  COPY Release/usb.a
  CXX(target) Release/obj.target/usb_bindings/src/node_usb.o
In file included from ../src/helpers.h:3,
                 from ../src/node_usb.h:21,
                 from ../src/node_usb.cc:1:
../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWor                                                                                    ker*)’:
../node_modules/nan/nan.h:2232:62: warning: cast between incompatible function t                                                                                    ypes from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_                                                                                    cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2232 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from ../src/node_usb.h:14,
                 from ../src/node_usb.cc:1:
../src/node_usb.cc: At global scope:
/root/.cache/node-gyp/12.19.0/include/node/node.h:727:43: warning: cast between                                                                                     incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::add                                                                                    on_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, vo                                                                                    id*)’} [-Wcast-function-type]
  727 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/root/.cache/node-gyp/12.19.0/include/node/node.h:761:3: note: in expansion of m                                                                                    acro ‘NODE_MODULE_X’
  761 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_                                                                                    usage)
      |   ^~~~~~~~~~~~~
../src/node_usb.cc:95:1: note: in expansion of macro ‘NODE_MODULE’
   95 | NODE_MODULE(usb_bindings, Initialize)
      | ^~~~~~~~~~~
../src/node_usb.cc: In function ‘void handleHotplug(std::pair<libusb_device*, li                                                                                    busb_hotplug_event>)’:
../src/node_usb.cc:151:58: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::                                                                                    Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated [-Wde                                                                                    precated-declarations]
  151 |  Nan::MakeCallback(Nan::New(hotplugThis), "emit", 2, argv);
      |                                                          ^
In file included from ../src/helpers.h:3,
                 from ../src/node_usb.h:21,
                 from ../src/node_usb.cc:1:
../node_modules/nan/nan.h:1001:46: note: declared here
 1001 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../src/node_usb.cc:151:58: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::                                                                                    Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated [-Wde                                                                                    precated-declarations]
  151 |  Nan::MakeCallback(Nan::New(hotplugThis), "emit", 2, argv);
      |                                                          ^
In file included from ../src/helpers.h:3,
                 from ../src/node_usb.h:21,
                 from ../src/node_usb.cc:1:
../node_modules/nan/nan.h:1001:46: note: declared here
 1001 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
In file included from ../src/node_usb.h:12,
                 from ../src/node_usb.cc:1:
/root/.cache/node-gyp/12.19.0/include/node/v8.h: In instantiation of ‘void v8::P                                                                                    ersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::We                                                                                    akCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCal                                                                                    lbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)                                                                                    ]’:
/root/.cache/node-gyp/12.19.0/include/node/node_object_wrap.h:85:78:   required                                                                                     from here
/root/.cache/node-gyp/12.19.0/include/node/v8.h:10226:16: warning: cast between                                                                                     incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callba                                                                                    ck’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callbac                                                                                     ’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
10226 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/12.19.0/include/node/v8.h: In instantiation of ‘void v8::P                                                                                    ersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::We                                                                                    akCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCall                                                                                    backInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’                                                                                    :
../node_modules/nan/nan_object_wrap.h:65:61:   required from here
/root/.cache/node-gyp/12.19.0/include/node/v8.h:10226:16: warning: cast between                                                                                     incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callbac                                                                                    k’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’                                                                                     {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
  CXX(target) Release/obj.target/usb_bindings/src/device.o
In file included from ../src/helpers.h:3,
                 from ../src/node_usb.h:21,
                 from ../src/device.cc:1:
../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWor                                                                                    ker*)’:
../node_modules/nan/nan.h:2232:62: warning: cast between incompatible function t                                                                                    ypes from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_                                                                                    cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2232 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
../src/device.cc: In member function ‘void Req::submit(Device*, v8::Local<v8::Fu                                                                                    nction>, uv_work_cb, uv_work_cb)’:
../src/device.cc:220:70: warning: cast between incompatible function types from                                                                                     ‘uv_work_cb’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(u                                                                                    v_work_s*, int)’} [-Wcast-function-type]
  220 |   uv_queue_work(uv_default_loop(), &req, backend, (uv_after_work_cb) aft                                                                                    er);
      |                                                                      ^~~                                                                                    ~~
../src/device.cc: In static member function ‘static void Req::default_after(uv_w                                                                                    ork_t*)’:
../src/device.cc:237:64: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Lo                                                                                    cal<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprec                                                                                    ated [-Wdeprecated-declarations]
  237 |    Nan::MakeCallback(device, Nan::New(baton->callback), 1, argv);
      |                                                                ^
In file included from ../src/helpers.h:3,
                 from ../src/node_usb.h:21,
                 from ../src/device.cc:1:
../node_modules/nan/nan.h:959:46: note: declared here
  959 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../src/device.cc:237:64: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Lo                                                                                    cal<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprec                                                                                    ated [-Wdeprecated-declarations]
  237 |    Nan::MakeCallback(device, Nan::New(baton->callback), 1, argv);
      |                                                                ^
In file included from ../src/helpers.h:3,
                 from ../src/node_usb.h:21,
                 from ../src/device.cc:1:
../node_modules/nan/nan.h:959:46: note: declared here
  959 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
In file included from ../src/node_usb.h:12,
                 from ../src/device.cc:1:
/root/.cache/node-gyp/12.19.0/include/node/v8.h: In instantiation of ‘void v8::P                                                                                    ersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::We                                                                                    akCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCal                                                                                    lbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)                                                                                    ]’:
/root/.cache/node-gyp/12.19.0/include/node/node_object_wrap.h:85:78:   required                                                                                     from here
/root/.cache/node-gyp/12.19.0/include/node/v8.h:10226:16: warning: cast between                                                                                     incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callba                                                                                    ck’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callbac                                                                                     ’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
10226 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/12.19.0/include/node/v8.h: In instantiation of ‘void v8::P                                                                                    ersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::We                                                                                    akCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCall                                                                                    backInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’                                                                                    :
../node_modules/nan/nan_object_wrap.h:65:61:   required from here
/root/.cache/node-gyp/12.19.0/include/node/v8.h:10226:16: warning: cast between                                                                                     incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callbac                                                                                    k’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’                                                                                     {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
  CXX(target) Release/obj.target/usb_bindings/src/transfer.o
In file included from ../src/helpers.h:3,
                 from ../src/node_usb.h:21,
                 from ../src/transfer.cc:1:
../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../node_modules/nan/nan.h:2232:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2232 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
../src/transfer.cc: In function ‘void handleCompletion(Transfer*)’:
../src/transfer.cc:126:72: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  126 |   Nan::MakeCallback(self->handle(), Nan::New(self->v8callback), 3, argv);
      |                                                                        ^
In file included from ../src/helpers.h:3,
                 from ../src/node_usb.h:21,
                 from ../src/transfer.cc:1:
../node_modules/nan/nan.h:959:46: note: declared here
  959 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../src/transfer.cc:126:72: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  126 |   Nan::MakeCallback(self->handle(), Nan::New(self->v8callback), 3, argv);
      |                                                                        ^
In file included from ../src/helpers.h:3,
                 from ../src/node_usb.h:21,
                 from ../src/transfer.cc:1:
../node_modules/nan/nan.h:959:46: note: declared here
  959 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
In file included from ../src/node_usb.h:12,
                 from ../src/transfer.cc:1:
/root/.cache/node-gyp/12.19.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/root/.cache/node-gyp/12.19.0/include/node/node_object_wrap.h:85:78:   required from here
/root/.cache/node-gyp/12.19.0/include/node/v8.h:10226:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
10226 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/12.19.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../node_modules/nan/nan_object_wrap.h:65:61:   required from here
/root/.cache/node-gyp/12.19.0/include/node/v8.h:10226:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
  SOLINK_MODULE(target) Release/obj.target/usb_bindings.node
  COPY Release/usb_bindings.node
make: Leaving directory '/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/usb/build'

> @abandonware/bluetooth-hci-socket@0.5.3-6 install /usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/bluetooth-hci-socket
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-6/bluetooth_hci_socket-0.5.3-6-node-v72-linux-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for @abandonware/bluetooth-hci-socket@0.5.3-6 and node@12.19.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)
make: Entering directory '/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/bluetooth-hci-socket/build'
  CXX(target) Release/obj.target/bluetooth_hci_socket/src/BluetoothHciSocket.o
In file included from /root/.cache/node-gyp/12.19.0/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/root/.cache/node-gyp/12.19.0/include/node/node.h:727:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  727 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/root/.cache/node-gyp/12.19.0/include/node/node.h:761:3: note: in expansion of macro ‘NODE_MODULE_X’
  761 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/BluetoothHciSocket.cpp:578:1: note: in expansion of macro ‘NODE_MODULE’
  578 | NODE_MODULE(binding, BluetoothHciSocket::Init);
      | ^~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/bluetooth_hci_socket.node
  COPY Release/bluetooth_hci_socket.node
  COPY /usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/bluetooth-hci-socket/build'

> @abandonware/noble@1.9.2-10 install /usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble
> node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/build'
  SOLINK_MODULE(target) Release/obj.target/noble.node
  COPY Release/noble.node
make: Leaving directory '/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/build'
+ homebridge-mi-hygrothermograph@3.0.2
added 185 packages from 176 contributors in 64.456s`

**Comment by hannseman** [comment]
No problem, thanks for closing!
