### ISSUE TITLE
Hygrothermograph 2 / LYWSD03MMC not work its not possible to get data from that sensor

### ISSUE THREAD

**Issue by nerlic** [hannseman/homebridge-mi-hygrothermograph#119]
### Versions

- **homebridge**: `homebridge --version`
- **homebridge-mi-hygrothermograph**: `npm list --depth 1 --global homebridge-mi-hygrothermograph`
- **node**:       `node --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by hannseman** [comment]
It's working for other people and since you gav no details about the issue I'm closing this. Also see https://github.com/hannseman/homebridge-mi-hygrothermograph/issues/101
