### ISSUE TITLE
Unsupported platform for xpc-connection

### ISSUE THREAD

**Issue by xuyiduo** [hannseman/homebridge-mi-hygrothermograph#12]
pi@raspberrypi:~ $ sudo npm install -g --unsafe-perm homebridge-mi-hygrothermograph
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/homebridge-mi-hygrothermograph/node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ homebridge-mi-hygrothermograph@1.5.0
updated 1 package in 107.426s

My device is raspberry pi zeroW arm6l

**Comment by hannseman** [comment]
Hi! Do you have any problems? These warnings are just warnings about _optional_ dependencies not being installed. `xpc-connection` is only required when running macOS.

**Comment by xuyiduo** [comment]
感谢关注我的问题！
安装完成后启动HB错误。

sudo npm uninstall -g homebridge-mi-hygrothermograph
恢复正常。

唯一提示的错误就是上面所述的。

**Comment by hannseman** [comment]
So homebridge crashes after you install this plugin? Could you please check the homebridge logs and paste the output here?

**Comment by hannseman** [comment]
Closing this issue as there was no follow up.
