### ISSUE TITLE
Only the first device has config-ui-x settings

### ISSUE THREAD

**Issue by NewsGuyTor** [hannseman/homebridge-mi-hygrothermograph#122]
This isn't really the biggest issue (since changing the config.json manually is so easy), but I just noticed that the settings for only the first Hygrothermograph listed in config.json is accessible through the Homebridge Config UI settings.

**Comment by ethempekin** [comment]
I have some difficulty in understanding to modify the config.json for accomodating more than more devices. can you share it here?

**Comment by NewsGuyTor** [comment]
```    "accessories": [
        {
            "name": "Thermometer-Kitchen",
            "address": "28:2A:34:30:21:8D",
            "temperatureName": "Temperature",
            "humidityName": "Humidity",
            "fakeGatoEnabled": true,
            "timeout": 15,
            "forceDiscovering": true,
            "forceDiscoveringDelay": 2500,
            "disableBatteryLevel": false,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "accessory": "Hygrotermograph"
        },
        {
            "name": "Thermometer-Outside",
            "address": "58:2D:34:31:21:7B",
            "temperatureName": "Temperature",
            "humidityName": "Humidity",
            "fakeGatoEnabled": true,
            "timeout": 60,
            "forceDiscovering": true,
            "forceDiscoveringDelay": 2000,
            "disableBatteryLevel": false,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "accessory": "Hygrotermograph"
        }
```

**Comment by hannseman** [comment]
Just released a new version where it should be possible to configure multiple devices in `config-ui-x`, let me know if it works. Thanks!

**Comment by ethempekin** [comment]
Super thanks for the update. Also for @NewsGuyTor for the config. Running two sensors now but struggling with timing out of one. While I have good coverage of wifi (via airport express to extend wifi) in the attic sensor is not working reliable. RPi where homebridge is running is down 2 floors in the ground floor.

**Comment by hannseman** [comment]
@ethempekin these sensors do not rely on wifi but Bluetooth. I've had range issues myself caused by too thick concrete walls. Bluetooth range is unfortunately quite limited. One solution is to use another raspberry pi with homebridge on the floor that you've got issues with. Good luck!

**Comment by ethempekin** [comment]
Makes sense. Thanks.
