### ISSUE TITLE
Xiaomy sensor reports incorrect miflora data

### ISSUE THREAD

**Issue by alexbell62** [hannseman/homebridge-mi-hygrothermograph#123]
Xiaomi sensor reports incorrect miflora data:
- moisture incorrectly called humidity
- soil fertility / conductivity is missing in home assistant, but when look at http://192.168.86.37:6415/entities there is following:
{"attributes":{},"id":"avocado-null","name":"avocado null","distributed":false,"state":338}
which is (338) the same as soild fertility when looking at the app.
- battery level is missing

To reproduce
- Install miflora sensor like that one: 
https://www.google.com/search?sxsrf=ALeKk01rwYVimarlcLpKctYy1WiXBiLDmw%3A1606235465771&ei=STW9X965LoPBgQaQ84zwDA&q=mi+flora&oq=mi+flora&gs_lcp=CgZwc3ktYWIQAzIECCMQJzIFCAAQkQIyBggAEAcQHjIGCAAQBxAeMgYIABAHEB4yBggAEAcQHjIICAAQBxAKEB4yBggAEAcQHjIGCAAQBxAeMgIIAFDnbljnbmCQcGgAcAB4AIABd4gBrQKSAQMxLjKYAQCgAQGqAQdnd3Mtd2l6wAEB&sclient=psy-ab&ved=0ahUKEwiegvOyzZvtAhWDYMAKHZA5A84Q4dUDCA0&uact=5

**Comment by hannseman** [comment]
Thanks for your report. The miflora is currently not supported and it's already reported in this issue https://github.com/hannseman/homebridge-mi-hygrothermograph/issues/44

Closing as duplicate.
