### ISSUE TITLE
Homebridge.err increases very rapidly the size

### ISSUE THREAD

**Issue by magnificent3** [hannseman/homebridge-mi-hygrothermograph#13]
I’ve been using this plugin and i maxed my sd card size very fast through the homebridge.err log file using three sensors.
Is there a way to get around this issue?

**Comment by hannseman** [comment]
What are the contents of the log-file?

Are you running homebridge with the debug-flag enabled `homebridge -D`?  Or are you settings the debug environment-variable? `DEBUG=*` If so, please turn those off. Especially running with `DEBUG=*` will produce large amounts if logs as it will enable the debug-logging on the low-level bluetooth API:s that are used.

**Comment by magnificent3** [comment]
Yes! That was it! Running on debug environment did produce a massive information of the Bluetooth API.
Disabled debug environment and now no long massive logging.
Thanks for your help!
Btw Amazing job!
