### ISSUE TITLE
Homebridge stops when adding sensors

### ISSUE THREAD

**Issue by Lars83** [hannseman/homebridge-mi-hygrothermograph#132]
When inserting the sensors in the config, the Homebridge no longer starts

As soon as I have inserted a sensor in the config, the following error is displayed in the log and the Homebridge no longer starts.

Error: ENODEV, No such device
    at Hci.init (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100:35)
    at NobleBindings.init (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:78:13)
    at /usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/noble.js:60:24
    at processTicksAndRejections (internal / process / task_queues.js: 75: 11)

I have already set up my Homebridge and reinstalled the plugin, but unfortunately without success so far.
If I have the entries from the Config. then remove the Hoemebridge runs cleanly.

homebridge: v1.1.7
homebridge-mi-hygrothermograph: v3.0.3
node: v14.15.4
OS: Raspbian GNU / Linux Buster (10)

 "name": "room climate guest room",
            "address": "xx",
            "bindKey": "xx",
            "temperatureName": "temperature",
            "humidityName": "humidity",
            "fakeGatoEnabled": true,
            "timeout": 15,
            "forceDiscovering": true,
            "forceDiscoveringDelay": 2500,
            "updateInterval": 60,
            "disableBatteryLevel": false,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "accessory": "Hygrotermograph"
        },
        {
            "name": "room climate office",
            "address": "xx",
            "bindKey": "xx",
            "temperatureName": "temperature",
            "humidityName": "humidity",
            "fakeGatoEnabled": true,
            "timeout": 15,
            "forceDiscovering": true,
            "forceDiscoveringDelay": 2500,
            "updateInterval": 60,
            "disableBatteryLevel": false,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "accessory": "Hygrotermograph"
        },
        {
            "name": "indoor climate bathroom",
            "address": "xx",
            "bindKey": "xx",
            "temperatureName": "temperature",
            "humidityName": "humidity",
            "fakeGatoEnabled": true,
            "timeout": 15,
            "forceDiscovering": true,
            "forceDiscoveringDelay": 2500,
            "updateInterval": 60,
            "disableBatteryLevel": false,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "accessory": "Hygrotermograph"
        },
        {
            "name": "Kitchen room climate",
            "address": "xx",
            "bindKey": "xx",
            "temperatureName": "temperature",
            "humidityName": "humidity",
            "fakeGatoEnabled": true,
            "timeout": 15,
            "forceDiscovering": true,
            "forceDiscoveringDelay": 2500,
            "updateInterval": 60,
            "disableBatteryLevel": false,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "accessory": "Hygrotermograph"
        },
        {
            "name": "room climate bedroom",
            "address": "xx",
            "bindKey": "xx",
            "temperatureName": "temperature",
            "humidityName": "humidity",
            "fakeGatoEnabled": true,
            "timeout": 15,
            "forceDiscovering": true,
            "forceDiscoveringDelay": 2500,
            "updateInterval": 60,
            "disableBatteryLevel": false,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "accessory": "Hygrotermograph"
        },
        {
            "name": "indoor climate living room",
            "address": "xx",
            "bindKey": "xx",
            "temperatureName": "temperature",
            "humidityName": "humidity",
            "fakeGatoEnabled": true,
            "timeout": 15,
            "forceDiscovering": true,
            "forceDiscoveringDelay": 2500,
            "updateInterval": 60,
            "disableBatteryLevel": false,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "accessory": "Hygrotermograph"
        },

**Comment by hannseman** [comment]
Something is wrong with how Bluetooth is set up on your system. Found this issue which might help you: https://raspberrypi.stackexchange.com/questions/47045/hcitool-scan-says-no-such-device

**Comment by Lars83** [comment]
Unfortunately, I can't do it as it is described there, you could help me with it
