### ISSUE TITLE
Support for Polling Requests

### ISSUE THREAD

**Issue by Alperen-Ozturk** [hannseman/homebridge-mi-hygrothermograph#133]
As you know Hygrothermograph 2 / LYWSD03MMC sensor passively broadcasts temp/humidity value every 10 minutes, and battery status hourly. This interval is too much for many peoples use case. I was wondering if you could implement a polling request feature so the sensor can actively broadcast current values based on the interval we set?

**Comment by hannseman** [comment]
You can use `updateInterval` to avoid updating HomeKit to often.
