### ISSUE TITLE
Peripheral Discovered but no event and not responding in Home App

### ISSUE THREAD

**Issue by SimBro2708** [hannseman/homebridge-mi-hygrothermograph#134]
I did the steps as shown in the post. I used the Telink website to get the bindKey. The only step which didn´t work was setting the permissions "**setcap cap_net_raw+eip $(eval readlink -f `which node`)**" which gave me the error "**unable to set CAP_SETFCAP effective capability: Operation not permitted**". I googled this topic but couldn´t find anything helpfull.
I´m assuming that it´s seeing the sensor but thinks that there is nothing to read?
I reinstalled the Plugin a few times, tested it which other sensors but I just won´t work.

**### Versions**
**Homebridge Version**
1.2.5

**### mi-hygrothermograph Version**
homebridge-mi-hygrothermograph@3.0.3

**### Node Version**
14.15.4

**###iOS Version**
14.4

**### Configuration**
        {
            "name": "TemperatureHumidity",
            "temperatureName": "Temperature",
            "humidityName": "Humidity",
            "fakeGatoEnabled": false,
            "timeout": 15,
            "forceDiscovering": false,
            "disableBatteryLevel": false,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "bindKey": "e95d21eb1ce4a370dac96ed2a1551508",
            "accessory": "Hygrotermograph"
        }

### Homebridge Log
[04/02/2021, 17:54:09] [TemperatureHumidity] [a4:c1:38:11:a6:46] Discovered peripheral
      Id: a4c13811a646
      LocalName: LYWSD03MMC
      rssi: -37
      serviceData: 30585b050c46a61138c1a408
[04/02/2021, 17:54:09] [TemperatureHumidity] No event

**Comment by hannseman** [comment]
You need to run `setcap` with `sudo`.

**Comment by sbmueller** [comment]
I don't have a `node` executable in PATH, is there a specific location Homebridge installs it into?
