### ISSUE TITLE
Help to implement FakeElGato History to another PlugIn

### ISSUE THREAD

**Issue by GSanCap** [hannseman/homebridge-mi-hygrothermograph#14]
Can you fork and implement Fake El Gato History to homebridge-mqtt-temperature-tasmota plugin as contributor?

Thanks in advance :)

**Comment by hannseman** [comment]
Hi! If you have interest in adding/having support for fakegato-history you should open an issue/pull request on [MacWyznawca/homebridge-mqtt-temperature-tasmota](https://github.com/MacWyznawca/homebridge-mqtt-temperature-tasmota).
