### ISSUE TITLE
can't find the mac address

### ISSUE THREAD

**Issue by hbkmanbass** [hannseman/homebridge-mi-hygrothermograph#142]
Dear users, 

I cannot find the mac address of my device Hygrothermograph 2 / LYWSD03MMC 

I'm on Macos. I have read the readme but I cannot find the solution. 

Thanks in advance,

**Comment by bnussbau** [comment]
You can use a Bluetooth Utility on the mac. e.g. 
* Bluesee: https://apps.apple.com/us/app/bluesee-ble-debugger/id1336679524?mt=12
* Bluetility: https://github.com/jnross/Bluetility/releases
or Apple PacketLogger from XCode Additional Tools

Also if you start homebridge in Debug mode you should see logs.

**Comment by hbkmanbass** [comment]
Thank you for your fast answer !
