### ISSUE TITLE
LYWSD03MMC no connection

### ISSUE THREAD

**Issue by mvoss96** [hannseman/homebridge-mi-hygrothermograph#143]
I'm trying to pair a LYWSD03MMC sensor to my homebridge running on a rpi4.
The sensor works flawlessly in the mihome app and i got the ble key using the cloud extractor.

my config looks like this:
{
            "name": "Temperature & Humidity",
            "address": "A4:C1:38:A1:18:C7",
            "temperatureName": "Temperature",
            "humidityName": "Humidity",
            "fakeGatoEnabled": false,
            "timeout": 15,
            "forceDiscovering": true,
            "forceDiscoveringDelay": 2500,
            "disableBatteryLevel": false,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "accessory": "Hygrotermograph",
            "bindKey": "A76B571F0F81B083999B8B7C73F4EFBC"
        }

however, in the home bridge log, I'm only getting the following:
[16/04/2021, 11:49:03] [Temperature & Humidity] Initializing Hygrotermograph accessory...

no other lines from this plugin and temperature and humidity remain at 0.
Any idea what went wrong?

Thanks in advance.

**Comment by mvoss96** [comment]
Ok, i was able to connect to the sensors, but only after flashing the custom firmware on them.

**Comment by hannseman** [comment]
Cool! Feel free to add a section about that process in a PR. I think that would help others who struggle with that device.

**Comment by lukyer** [comment]
@mvoss96  @hannseman 👋  do you remember which firmware/flasher did you exactly use? I'm trying to add some  LYWSD03MMC sensors to my homebridge but with no luck. Other Xiaomi (rounded) sensors work OK. I have tried 3 firmwares already, with and without bindKey, several flashers but still no luck. These tools/xiaomi app can detect temperature without any problems. Thanks!
