### ISSUE TITLE
Is there any ablity to use Xiaomi Hygrothermometer for AC temperature value?

### ISSUE THREAD

**Issue by Ugmaxie** [hannseman/homebridge-mi-hygrothermograph#15]
Hey, great thanks for your hard work for a community.

Could you assist, please, with an ability to use Xiaomi Hygrothermometer as a temperature sensor for air-conditioner?
I'm using a [certain plugin](https://github.com/lprhodes/homebridge-broadlink-rm) for that.

As I know - homebridge modules don't know about each other at all, so I have to link it somehow...

**Comment by GSanCap** [comment]
For this ability the plugin must write the temperature value to a MQTT Topic, @hannseman can you add this new function? maybe can i help to implement.

Regards

**Comment by Ugmaxie** [comment]
Sure, I've tried to investigate this, but have no knowledge in this topic in order to implement MQTT Brokers and Clients.
So @hannseman , it really should be a good upgrade if you do that. :+1:

**Comment by hannseman** [comment]
Good idea! I'll look into adding support for publishing the values to MQTT.

**Comment by GSanCap** [comment]
@hannseman you rocks!

**Comment by hannseman** [comment]
Support for this have been implemented in #16. I'll make a release ASAP but if you want to try it out please go ahead and install directly from that branch.

**Comment by Ugmaxie** [comment]
A huge **Thank you**, @hannseman , for your work! :) 
Great time to make a release :)

**Comment by hannseman** [comment]
Fixed in [v1.7.0](https://github.com/hannseman/homebridge-mi-hygrothermograph/tree/v1.7.0)

**Comment by justradojko** [comment]
Will configuring of MQTT enable Xiaomi Hygrothermometer to be used as sensor in automation section of HomeKit app?

**Comment by GSanCap** [comment]
> Will configuring of MQTT enable Xiaomi Hygrothermometer to be used as sensor in automation section of HomeKit app?

No, HomeKit doesn´t support automations based in Temperature sensors, you need to use another homebridge plugin that uses the hygromether via MQTT as temperature sensor, fox example, i use the homebridge-broadlink-rm plugin to control the AC and use the Hygromether as temperature sensor via MQTT
