### ISSUE TITLE
LYWSD03MMC on OS X

### ISSUE THREAD

**Issue by Pablo-Githu** [hannseman/homebridge-mi-hygrothermograph#152]
Im triying to connect LYWSD03MMC to MacMini server.

I have all ready try to install everithing reading the instructions, but there are several commands that are incompatible in mac os.

Please can you help with a detailed step to step guide?

I have changed firmware to avoid encription with this: https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html

I have success conneting the sensor, but cant se it on hombridege, neither homekit.

![image](https://user-images.githubusercontent.com/49842434/115975340-ef32da80-a531-11eb-91e4-afb1686ed40a.png)

![image](https://user-images.githubusercontent.com/49842434/115975353-fc4fc980-a531-11eb-9994-2c31162ef389.png)

### Versions

- **homebridge**: 1.3.4 (UI)
- **homebridge-mi-hygrothermograph**: homebridge-mi-hygrothermograph@3.1.0
- **node**:       v14.16.1
- **OS**:         OS X / CATALINA

### Logs

[CLIMA CASA] Initializing Hygrotermograph accessory...

### Configuration

 {
            "name": "CLIMA CASA",
            "address": "a4:c1:38:51:ca:f8",
            "temperatureName": "Temperatura",
            "humidityName": "Humedad",
            "fakeGatoEnabled": false,
            "timeout": 15,
            "forceDiscovering": true,
            "forceDiscoveringDelay": 2500,
            "disableBatteryLevel": false,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "bindKey": "a2:e2:5c:55:c6:25:71:07:10:01:68:4a:6c:1e:9a:f8",
            "accessory": "Hygrotermograph"
        }

Thanks in advance for any help.

**Comment by Pablo-Githu** [comment]
i make it work!!

**Comment by netosha** [comment]
How you fix it?
