### ISSUE TITLE
plugin crashes or devices do not respond in hoobs 4

### ISSUE THREAD

**Issue by saiajin** [hannseman/homebridge-mi-hygrothermograph#154]
### Versions

- **homebridge**: `Hoobs 4.0.58
- **homebridge-mi-hygrothermograph**: `npm list --depth 1 --global homebridge-mi-hygrothermograph`
- **node**:       `node --version`
- **OS**:         

### Configuration

```{
    "accessories": [
        {
            "name": "Master Bedroom Temperature & Humidity",
            "address": "E7:2E:00:71:F4:72",
            "temperatureName": "Temperature",
            "humidityName": "Humidity",
            "timeout": 15,
            "forceDiscoveringDelay": 2500,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "accessory": "Hygrotermograph",
            "forceDiscovering": true,
            "updateInterval": 1,
            "fakeGatoEnabled": false
        },
        {
            "name": "Master Bathroom Temperature & Humidity",
            "address": "A4:C1:38:96:9E:56",
            "temperatureName": "Temperature",
            "humidityName": "Humidity",
            "timeout": 15,
            "bindKey": "3b27824aa7a7bbc84954636378d46baf",
            "forceDiscoveringDelay": 2500,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "accessory": "Hygrotermograph",
            "updateInterval": 1,
            "forceDiscovering": true
        },
        {
            "name": "Office Temperature & Humidity",
            "temperatureName": "Temperature",
            "humidityName": "Humidity",
            "timeout": 15,
            "bindKey": "15cc50d755dafac06da6976991170729",
            "forceDiscoveringDelay": 2500,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "accessory": "Hygrotermograph",
            "updateInterval": 1,
            "address": "A4:C1:38:9B:BF:7B",
            "forceDiscovering": true
        }
    ],
    "platforms": []
}
```

### Homebridge Log / Command Output
5/4/2021, 12:27:08 AM
Mi Hygrothermograph Bridge
Loaded plugin 'homebridge-mi-hygrothermograph'
5/4/2021, 12:27:11 AM
Mi Hygrothermograph Bridge
Loading 3 accessories...
5/4/2021, 12:27:12 AM
Mi Hygrothermograph Bridge
ERROR
Error: ENODEV, No such device at Hci.init (/var/lib/hoobs/mihygrothermographbridge/node_modules/@abandonware/noble/lib/hci-socket/hci.js:120:18) at NobleBindings.init (/var/lib/hoobs/mihygrothermographbridge/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:93:13) at /var/lib/hoobs/mihygrothermographbridge/node_modules/@abandonware/noble/lib/noble.js:61:24 at processTicksAndRejections (internal/process/task_queues.js:75:11)
5/4/2021, 12:27:22 AM
Mi Hygrothermograph Bridge starting
5/4/2021, 12:27:25 AM
Mi Hygrothermograph Bridge
Loaded plugin 'homebridge-mi-hygrothermograph'
5/4/2021, 12:27:29 AM
Mi Hygrothermograph Bridge
Loading 3 accessories...
5/4/2021, 12:27:29 AM
Mi Hygrothermograph Bridge
ERROR
Error: ENODEV, No such device at Hci.init (/var/lib/hoobs/mihygrothermographbridge/node_modules/@abandonware/noble/lib/hci-socket/hci.js:120:18) at NobleBindings.init (/var/lib/hoobs/mihygrothermographbridge/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:93:13) at /var/lib/hoobs/mihygrothermographbridge/node_modules/@abandonware/noble/lib/noble.js:61:24 at processTicksAndRejections (internal/process/task_queues.js:75:11)
5/4/2021, 12:27:39 AM
Mi Hygrothermograph Bridge starting
5/4/2021, 12:27:43 AM
Mi Hygrothermograph Bridge
Loaded plugin 'homebridge-mi-hygrothermograph'
5/4/2021, 12:27:46 AM
Mi Hygrothermograph Bridge
Loading 3 accessories...
5/4/2021, 12:27:46 AM
Mi Hygrothermograph Bridge
ERROR
Error: ENODEV, No such device at Hci.init (/var/lib/hoobs/mihygrothermographbridge/node_modules/@abandonware/noble/lib/hci-socket/hci.js:120:18) at NobleBindings.init (/var/lib/hoobs/mihygrothermographbridge/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:93:13) at /var/lib/hoobs/mihygrothermographbridge/node_modules/@abandonware/noble/lib/noble.js:61:24 at processTicksAndRejections (internal/process/task_queues.js:75:11)

```

```

**Comment by hannseman** [comment]
There is something wrong with your setup. No bluetooth device can be found, please check `hciconfig` and make sure that you've followed the instructions in the README for how to install all dependencies and make sure that non-root users can access bluetooth.

**Comment by saiajin** [comment]
Hmmm.. Well the Clock Hygrothermometer intermittently shows up... so it seems to find them occasionally? Hoobs has been updated since I posted this and the logs arent as verbose...
