### ISSUE TITLE
Temperature 0° and humidity 0%

### ISSUE THREAD

**Issue by kiwidutchhome** [hannseman/homebridge-mi-hygrothermograph#159]
### Expected Behavior
I expect to see the temperature and humidity sensor (Xiaomi Mi LYWSD03MMC) reading in Homebridge ui and then in Homekit. 
 
### Current Behavior
Homebridge UI says my temperature is 0° and humidity is 0%

But my sensor says 23.7° and humidity of 52%

### Steps to Reproduce (for bugs)

Installed the homebridge-mi-hygrothermograph plugin in Homebriddge ui
It did not work so I did
sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev
To make sure noble was up-to-date
Then I did 
sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)

Nothing works. 

### Versions

- **homebridge**: 1.3.4
- **homebridge-mi-hygrothermograph**: 3.1.0
- **node**:       14.17.4
- **OS**:         *** Homebridge Raspbian v1.0.24 - Raspberry Pi 4 Model B Rev 1.2 ***

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "0E:17:FD:92:04:6A",
        "port": 51948,
        "pin": "130-07-028"
    },
    "accessories": [
        {
            "type": "switch",
            "name": "mqtt broker",
            "url": "mqtt://192.168.1.118",
            "username": "?????",
            "password": "?????",
            "logMqtt": true,
            "accessory": "mqttthing"
        },
        {
            "name": "Bedroom Temperature & Humidity",
            "temperatureName": "Temperature",
            "humidityName": "Humidity",
            "fakeGatoEnabled": false,
            "timeout": 15,
            "forceDiscovering": true,
            "forceDiscoveringDelay": 2500,
            "disableBatteryLevel": false,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "bindKey": "c2cf79f5772cd1f445be265f83556bba",
            "accessory": "Hygrotermograph",
            "_bridge": {
                "username": "0E:51:0D:CB:1E:96",
                "port": 42079
            }
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Living room",
            "hubIP": "192.168.1.201",
            "hubName": "Living Room",
            "DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS": 60000,
            "HUB_CONNECT_TIMEOUT": 10000,
            "HUB_SEND_TIMEOUT": 30000,
            "publishAllTVAsExternalAccessory": true,
            "TVAccessory": false,
            "platform": "HarmonyHubWebSocket",
            "_bridge": {
                "username": ?????????
                "port":????????
            }
        },
        {
            "platform": "HarmonyHub",
            "name": "HarmonyHub"
        },
        {
            "name": "Aedes MQTT",
            "host": "192.168.1.118",
            "auth": {
                "isEnabled": true,
                "username": "???????",
                "password": "?????"
            },
            "platform": "HomebridgeAedes"
        }
    ]
}
  ``

### Homebridge Log / Command Output
<!-- Paste relevant output between the two ``` lines below
  - Remove any sensitive information, passwords, etc.
  - If output is long:
    - Please extract only the relevant portions if possible
    - Consider creating a gist, etc
  - However, please include the beginning of the log where the homebridge initialization happens if possible
-->
```
10/10/2021, 16:21:04] [Bedroom Temperature & Humidity] Loaded homebridge-mi-hygrothermograph v3.1.0 child bridge successfully
[10/10/2021, 16:21:04] [Bedroom Temperature & Humidity] address option is not set. When running multiple sensors this will cause interference. See README for instructions.
Preparing Advertiser for 'Bedroom Temperature & Humidity DD46' using bonjour-hap backend!
Starting to advertise 'Bedroom Temperature & Humidity DD46' using bonjour-hap backend!
[10/10/2021, 16:21:04] Homebridge v1.3.4 (Bedroom Temperature & Humidity) is running on port 42079.
```

**Comment by Tapsel99** [comment]
Mine too. 

[Thermostat] Error setting targetTemperature: ESOCKETTIMEDOUT

**Comment by hannseman** [comment]
@kiwidutchhome feels like Bluetooth is not set up properly on your system. Make sure that you’ve followed the README and try running `sudo hciconfig hci0 up` before starting homebridge.
