### ISSUE TITLE
Timed out

### ISSUE THREAD

**Issue by 49jpg** [hannseman/homebridge-mi-hygrothermograph#160]
After the last update of Hoobs all my sensors go in time out very often 

Mi Hygrothermograph Bridge Bathroom T&H WARNING[58:2D:34:33:66:FC] Timed out, last update: 2021-10-10T18:58:38.537Z

**Comment by Tapsel99** [comment]
Mine too.

[Thermostat] Error setting targetTemperature: ESOCKETTIMEDOUT

**Comment by hannseman** [comment]
@49jpg If it’s not constantly timing out it’s most likely a range issue. Try moving the sensor it closer to the raspberry pi and see if it helps. If it’s an RPI2 you’re having it’s know to have issues with connectivity, try using a newer RPI or a separate USB BLE dongle.

@Tapsel99 please stop spamming this in various issues. That error message doesn’t even look like it’s from this plugin.
