### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by chrisremie** [hannseman/homebridge-mi-hygrothermograph#164]
I'm trying to install the plugin from Homebridge UI, on a RaspberryPi W Zero.
Latest Raspbian-Homebridge image.

This is the end of the log file:

1037 timing reify:rollback:createSparse Completed in 19705ms
1038 timing reify:rollback:retireShallow Completed in 1ms
1039 timing command:install Completed in 412398ms
1040 verbose stack Error: process terminated
1040 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:194:39
1040 verbose stack     at process.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:51:5)
1040 verbose stack     at process.emit (node:events:402:35)
1041 verbose cwd /usr/local
1042 verbose Linux 5.10.63+
1043 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-mi-hygrothermograph@latest"
1044 verbose node v16.13.0
1045 verbose npm  v8.1.3
1046 error process terminated
1047 error signal SIGTERM
1048 verbose exit 1

**Comment by chrisremie** [comment]
It works with the previous version of the Raspbian-Homebridge image (and the latest Homebridge).
The difference is that the latest version uses Raspberry Pi OS Lite - Debian Bullseye (2021-10-30), Node.js Version: v16.13.0 and the previous version uses Raspbian Buster Lite (2021-05-07), Node.js Version: v14.18.1.

**Comment by hannseman** [comment]
Can you try running `npm install homebridge-mi-hygrothermograph` manually and paste any error you get.
