### ISSUE TITLE
'Current Temperature': characteristic was supplied illegal value: number -21.1 exceeded minimum of -10

### ISSUE THREAD

**Issue by mrrivest** [hannseman/homebridge-mi-hygrothermograph#173]
Title says it all. The plugin has a minimal value of -10c. If it's colder, it says the value is illegal.

### Expected Behavior
If it's -21.1c outside, it should report -21.1c, not -10c.

### Versions
 v3.1.0

**Comment by hannseman** [comment]
Fixed by #174
