### ISSUE TITLE
LYWSDCGQ01ZM not showing in EVE rooms

### ISSUE THREAD

**Issue by MontroseSt** [hannseman/homebridge-mi-hygrothermograph#193]
My LYWSDCGQ01ZM is showing in Eve- > Settings -> Accessories and I can also use it to create automations. However, it does not show up in the room that have assigned it to. Respectively, I can also not review the historical data that Eve stores.

Does anyone else have this problem?

**Comment by minuscorp** [comment]
I have the same issue here

**Comment by minuscorp** [comment]
Any comment about this?

**Comment by 2610** [comment]
It would seem things have changed in the eve app I’m using https://github.com/themarvi/homebridge-mi-hygrothermograph that has them appearing as air quality sensor but you can hide that to leave only the temp and humidity

**Comment by MontroseSt** [comment]
Thank you. Honestly I wouldn't know how to install it without a npm... also it appears that the themarvi fork has not been updated for a while. It would be amazing if @hannseman could add another type option to set it up as a "air quality sensor" and get Eve FakeGato working  again

**Comment by hannseman** [comment]
I just released `3.4.2` to npm which contains a fix for this. Sorry for the delay.

**Comment by MontroseSt** [comment]
Awesome, thank you so much @hannseman! Working perfectly.
