### ISSUE TITLE
Granularity of battery percentage

### ISSUE THREAD

**Issue by msh100** [hannseman/homebridge-mi-hygrothermograph#2]
This is more of a question, so sorry for raising an issue.

I have had the sensors for about a week and they both report 100% battery still. This is making me wonder if the number reported is as granular as single percentage units? Have you seen the battery fall this precisely? or does it drop in chunks?

Thanks for your help

**Comment by hannseman** [comment]
Hi! 

The battery is only reported in single percent units, i.e 99, 98, 97.

The sensor appears to be very energy efficient and my battery status is reported as 91% after around 2 months of usage.
