### ISSUE TITLE
It does't work.

### ISSUE THREAD

**Issue by creatorMao** [hannseman/homebridge-mi-hygrothermograph#20]

**Comment by creatorMao** [comment]
At my raspberry，it Linked. But in the debug mode,it says [Stop Scanning (Poweredoff)]   but in my view, 
 the mi-hygrothermograph's battery is use Lithium battery。

**Comment by creatorMao** [comment]
![image](https://user-images.githubusercontent.com/24838084/42122198-b014a0dc-7c70-11e8-8461-446127b4e5b0.png)

**Comment by hannseman** [comment]
Sounds like you haven’t properly initialized Bluetooth on your system. 

Have you tried running `sudo hciconfig hci0 up’ before starting homebridge? Also make sure that you’ve followed the installation instructions in the README.

**Comment by hannseman** [comment]
Ah that explains your problems! :-)
