### ISSUE TITLE
Access through Mijia BLE Gateway

### ISSUE THREAD

**Issue by DSchumacher2104** [hannseman/homebridge-mi-hygrothermograph#25]
Hallo!

I'm using a Xiaomi Mijia 1080P Smart IP Camera (aka Mi Home Security Camera) which provides a BLE gateway that reads the  Xiaomi Mi Bluetooth Temperature and Humidity Sensor and allows remote access to the temperatur and humidity data with Xiaomi Mi Home App. This also works with the new Xiaomi Mi Bedside Lamp, which provides the same BLE gateway.

Is it possible to connect the Xiaomi Mi Bluetooth Temperature and Humidity Sensor through this gateway with a Homebridge Plug-in to provide the temperature und humidity data in HomeKit?

Thanks for your work and help!

**Comment by hannseman** [comment]
Hi. Not really sure why you need to connect the temperature sensor to the Xiaomi Gateway. By using this plugin you do not need any gateway. The raw bluetooth data is parsed and made available to HomeKit. The only downside to this is that you cannot use the official Xiaomi App for viewing the temperature. If you really want to run the Xiaomi Gateway you'll need to find some other plugin - have a look at:

https://github.com/Maxmudjon/homebridge-mijia
https://github.com/snOOrz/homebridge-aqara

**Comment by hannseman** [comment]
I see. I don’t know of any homebridge plugin that can do this. Maybe you can write your own?

Maybe this repo can help you to hook into the camera:
https://github.com/Filipowicz251/mijia-1080P-hacks

If want to go the route of reading stuff of the Xiaomi servers you could use Charles Proxy to sniff the HTTP-traffic between the Xiaomi app and the servers and then implement your own client.

Have you tried running this plugin in parallel to the camera / bedlamp? Depending on their implementation it could work. This plugin never actually connects to the sensor but reads the data from BLE advertisement packets. This enables multiple parties to read the data at the same time. The Mi home app also behaves like this when reading temperature data directly from the sensor. I tried it by letting two iPhones read data from the same sensor at the same time and it worked just fine.

**Comment by DSchumacher2104** [comment]
Yes, it works perfect parallel with Bedside Lamp and your plugin on a Raspberry Pi Zero W. The BLE gateway in Bedside Lamp updates the temperatures in Mi Home App. I dont't have enough skills in programming a plugin, but i'm totally satisfied with your plugin. Thank you, great work!

**Comment by hannseman** [comment]
Thank you! Nice to hear that it worked out.
