### ISSUE TITLE
Values not refreshing

### ISSUE THREAD

**Issue by lukyer** [hannseman/homebridge-mi-hygrothermograph#27]
If fakeGatoEnabled == false then values are refreshed normally, but if fakeGatoEnabled is set to true, values ale recorded only once when homebridge is started. What is even more weird - if I scan bt devices using `sudo hcitool lescan` , homebridge will actually record this value even with fakeGatoEnabled set to true.

**Comment by hannseman** [comment]
Wow that is weird. What platform, what Node version and homebridge version are you running? 

Could you please provide homebridge log files for when you are experiencing this isssue.

Thanks

**Comment by lukyer** [comment]
Sorry for my wrong observation, it looks like it is not related to fakeGatoEnabled value after all. Now it looks like just it stops measuring after some time. Seems similar to other opened issues here. 
Now i am gathering debug info so we will see more!

Raspberry PI B, Node 8.11.1, Bluetooth dongle some noname probably (do not remember), Homebridge 0.4.45

**Comment by lukyer** [comment]
When timeout happens, bluetoothctl controller info is:
`[bluetooth]# show 5C:F3:70:63:95:57
Controller 5C:F3:70:63:95:57
	Name: raspberrypi
	Alias: raspberrypi
	Class: 0x480000
	Powered: yes
	Discoverable: no
	Pairable: yes
	UUID: Headset AG                (00001112-0000-1000-8000-00805f9b34fb)
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
	UUID: Audio Source              (0000110a-0000-1000-8000-00805f9b34fb)
	UUID: Handsfree Audio Gateway   (0000111f-0000-1000-8000-00805f9b34fb)
	Modalias: usb:v1D6Bp0246d052B
	Discovering: **no**`

When i start discovering by `scan on` homebridge works OK immediately. I can also see all those debug messages about discovered devices in log again.

**Comment by hannseman** [comment]
Thanks! Can you look in the homebridge logs for the message `Stopped scanning.`.

I’ve been digging around some noble related issues and found https://github.com/noble/noble/issues/223.

It describes that for some people the library stops scanning for devices when a Bluetooth connection is created to any device. Do you have any other Bluetooth devices that you use with the raspberry pi? Maybe another homebridge plugin?

If so could you please try and not connect to this device and see if you still see this issue.

A possible workaround could be to try and restart the scanning when this plugin discovers that it have been stopped. I’ll have a look at implementing this asap if we can confirm that this actually is the problem you’re seeing.

**Comment by lukyer** [comment]
Thanks for your help. 
I run homebridge with -D parameter but no "Stopped" keyword in journalctl logs are present. Do you have any information about how to debug better homebridge/this plugin? Maybe these logs are still hidden? I read something about DEBUG=* environment variable.

I searched for issues in noble and found that topic too. However I have clean rpi installation with nothing more than homebridge + this plugin. Nothing should be connecting anywhere.

**Comment by hannseman** [comment]
Weird! If you're not seeing `Stopped scanning` in the logs I really have no clue of what might be the issue. 

There is an issue where starting a scan with something like `bluetoothctl` and then `scan on` will cancel the scanning made by this plugin on some systems. So for example having another homebridge plugin which scans for a specific device and then connects to it would stop this plugin from scanning. I have implemented a fix for this which can be enabled by setting `forceDiscovering` to `true` in the configuration but since this does not appear to be your issue I doubt it will help. This fix is not published to npm yet but you can install from github if you want to try it out anyway.

To run with the global debug enabled you set the `DEBUG=*` environment variable for the process. If running from command line you should be fine by just running `DEBUG=* homebridge -D`. Note that this will output _a lot_  of debug information from third party packages like noble.

Unfortunately I think your best bet might be to try another bluetooth dongle or buying a newer raspberry pi with builtin bluetooth.

**Comment by lukyer** [comment]
I tried to clone actual master to my RPi and run `npm install` but it ends with:
```
root@raspberrypi:~/homebridge-mi-hygrothermograph# npm install  --unsafe-perm
(node:18755) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.71+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "--unsafe-perm"
npm ERR! cwd /root/homebridge-mi-hygrothermograph
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/homebridge-mi-hygrothermograph/npm-debug.log
npm ERR! not ok code 0
```

Any ideas how to make it working when package not upgraded in npm? :/ 

Thanks!

**Comment by hannseman** [comment]
Try `npm install hannseman/homebridge-mi-hygrothermograph#master`

**Comment by hannseman** [comment]
I've made an npm release. Please upgrade to `1.9.0` and try it out.

**Comment by hannseman** [comment]
Closing this issue as no feedback have been provided in over a month.
