### ISSUE TITLE
Homekit Automations

### ISSUE THREAD

**Issue by KaiserDexter** [hannseman/homebridge-mi-hygrothermograph#29]
Hello, i have my Xiaomi Hygro working fine in Homekit but i have a question.

Its possible create automations with this sensor?

I write this because when i try create a new auomation in homekit, i have disabled the option "A Sensor Detech Something"

Thanks

**Comment by hannseman** [comment]
Apple Homekit does not support automations based on temperature or humidity. Hopefully it will in some later iOS version.

**Comment by lukyer** [comment]
Any updates on this one? Or workarounds? I managed to combine temperature/humidity value with new shortcuts app but I'm missing some repeated or value change based trigger.

Example of my shortcut automation which could help us:
![IMG_7C0B7F949183-1](https://user-images.githubusercontent.com/3464342/65823836-fe6e7b00-e25d-11e9-9e4a-693c18e1e862.jpeg)
