### ISSUE TITLE
Showing up as contact sensor in the Home app

### ISSUE THREAD

**Issue by RobertN82** [hannseman/homebridge-mi-hygrothermograph#31]
Thanks for the plugin, however I've run into 2 issues.

When running Homebridge through 'sudo systemctl start homebridge', it does not show the device in the Home app.
If I just run 'homebridge', it adds an extra device and I can see it start/stop scanning, ie:

start new round of scan
[2018-12-20 10:22:55] [Temperate & Humidity] Stopped scanning.
[2018-12-20 10:22:57] [Temperate & Humidity] Start scanning.

However, the device it adds in the Home app shows up as a contact sensor 'ContactSensor_ContactSensor_feaa' ?

Not really sure where to go from here?
Here's my config file:

```
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:31",
    "port": 51826,
    "pin": "031-45-154"
  },
  "description": "HomeBridge RPI",

 "accessories": [
     {
       "accessory": "Hygrotermograph",
       "name": "Temperate & Humidity",
       "timeout": 15,
       "temperatureName": "Temperature",
       "humidityName": "Humidity",
       "fakeGatoEnabled": false
     }
 ],

 
  "platforms": [
     {
       "platform": "MiAqaraPlatform",
       "gateways": {
         "7811dcb7df05": "71D0E9E78A2E4A07"
       }
     },
        {
            "platform" : "yeelight",
            "name" : "yeelight"
        }
   ]
}
```

Any help is much appreciated. Thanks!

**Comment by hannseman** [comment]
Hi! That's very weird. Especially that you don't see any error messages in the homebridge log. 

Could you attach a screenshot of the bottom of the settings view for the contact sensor you're seeing, what I'm interested in is what's present in the Manufacturer, Serial Number, Model and Firmware fields. I'm almost certain that this sensor is something exposed by the aqara platform.

My guess on why the sensor isn't working is that you're not running it as root. You shouldn't run it as root but for it to function you need to give the node binary access to the bluetooth system as described in the readme.

Here you can read details of how to achieve this: https://github.com/noble/noble#running-without-rootsudo

**Comment by RobertN82** [comment]
![img_1989](https://user-images.githubusercontent.com/46020167/50730379-396ad480-114c-11e9-9717-ccdc23a74fa4.PNG)

This is the setting in the Home app.
I have some Aqara contact sensors, so I set the address in the config to 'force' it to use the correct device, but to no avail.

`
 "accessories": [
     {
       "accessory": "Hygrotermograph",
       "address": "4C:65:A8:D1:B4:12",
       "name": "Temperate & Humidity",
       "timeout": 15,
       "temperatureName": "Temperature",
       "humidityName": "Humidity",
       "fakeGatoEnabled": false
     }
 ],
`

**Comment by hannseman** [comment]
That contact sensor has nothing to do with this plugin. 

Please verify that you’ve configured your system to allow node access to bluetooth with setcap or that homebridge is running as root. 

I also need the full logs after a start up of homebridge with debug mode enabled.

**Comment by hannseman** [comment]
Closing this after no response in over a month. Feel free to request it to be opened again.
