### ISSUE TITLE
Low Battery not reported

### ISSUE THREAD

**Issue by GerSant** [hannseman/homebridge-mi-hygrothermograph#39]
### Expected Behavior
When the battery level is below to 20% LowBattery must be True

### Current Behavior
One of my Hygromether has 18% of Battery Level and Home App does not report the accesory as LowBattery

Thanks in advance

**Comment by hannseman** [comment]
Hi,

Why 20%? The battery on these devices last for so long that it really does not make sense to warn about low battery when it hits below 20%. It could have months left. Currently the threshold is at 10% and this will still give you weeks of usage before the battery needs to be replaced.

But we could add a configuration option to allow users set their own threshold.

**Comment by GerSant** [comment]
Its not necessary, you are right, 20% in BLE announcer devices its a lot of remaining power, 10% its OK.

Regards
