### ISSUE TITLE
Error when installing plugin

### ISSUE THREAD

**Issue by kamilzeliasz** [hannseman/homebridge-mi-hygrothermograph#42]
When I run "sudo npm install -g --unsafe-perm homebridge-mi-hygrothermograph" i got this error:

> npm ERR! Linux 3.16.63-37
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "homebridge-mi-hygrothermograph"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib/node_modules/.staging/assert-plus-d77bde99
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/assert-plus-d77bde99' -> '/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/assert-plus'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/assert-plus-d77bde99' -> '/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/assert-plus'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

My platform: Odroid C2, Ubuntu 18.04, Node v8.10.0, NPM v3.5.2

**Comment by hannseman** [comment]
Looks like som issue related to npm. You’re running a very old npm-version (over 3 years old). Upgrade npm and try again.
