### ISSUE TITLE
Adding support for @abandonware/noble

### ISSUE THREAD

**Issue by GerSant** [hannseman/homebridge-mi-hygrothermograph#45]
Noble its no more supported by te creator and no exist NodeJS v10 support, can you add support for the new NodeJS Fork with NodeJS v10 support? 

https://github.com/abandonware/noble

I update my system to NodeJS v10 and the plugin stops working when i try to install again

Thanks!

**Comment by GerSant** [comment]
Sorry my mistake i uninstall the @abandonware/bluetooth-hci-socket and reinstalled again and it works...sorry

**Comment by hannseman** [comment]
v2.0.0 supports node 10 by using that fork.
