### ISSUE TITLE
NOT ISSUE - New Xiaomi BLE Device

### ISSUE THREAD

**Issue by GerSant** [hannseman/homebridge-mi-hygrothermograph#46]
Hi, you think that you can create a homebridge plugin for this new accesory?

https://www.banggood.com/Xiaomi-Yeelight-Smart-bluetooth-Wireless-Wall-Pasted-Light-Switch-Work-With-Mihome-APP-p-1428204.html?rmmds=mywishlist&cur_warehouse=CN

Regards!

**Comment by hannseman** [comment]
Hi! Sorry I do not have this device.
