### ISSUE TITLE
NOT ISSUE - New Hygrothermograph support

### ISSUE THREAD

**Issue by josehipo** [hannseman/homebridge-mi-hygrothermograph#50]
Hello,
Thank you, I love your plugin!
Do you think will it work with the new Xiaomi Clock hygrothermograph?
https://item.mi.com/1191300012.html
![Unknown](https://user-images.githubusercontent.com/47568420/56891230-173eee80-6a7c-11e9-9c8d-f16c9bd661d3.jpg)

**Comment by hannseman** [comment]
Hi! Thanks for your kind words. 

I have no idea if it will work but probably not. There's also a new OLED-version of the device that this plugin was written for: https://cleargrass.com/cg_temp_rh_monitor/overview

Hopefully I can get my hands on these two devices ASAP and with a little luck get it working.

**Comment by merdok** [comment]
Hi,
i have both of them. The clock hygrothermograph and the new version which @hannseman posted. Both of them are e-ink displays and both of them work perfectly with your plugin :) 
Thanks for the great work!

**Comment by hannseman** [comment]
@merdok wow nice! I actually ordered both of them today. Thanks for the information.

I’ll close this issue for now. Let me know if there’s any trouble and I’ll reopen it.

**Comment by merdok** [comment]
@hannseman You mention in the README that the battery charge in percentage is also sent by the sensors but i do not see this information in HomeKit. Is it generally not implemented in the plugin or is this maybe an issue with the new sensors?

**Comment by hannseman** [comment]
@merdok the battery charge percentage should be visible on the sensor detail page. If this isn't the case with the new sensors I'll have a look at it once I have them in my possession :)

![IMG_1122](https://user-images.githubusercontent.com/758858/57190573-db90a280-6f1b-11e9-956b-e998e9403a9e.jpeg)

**Comment by merdok** [comment]
Unfortunately, this is not visible on the sensor detail page... There is only the next 

> Charging No

**Comment by hannseman** [comment]
Thanks for the response. I’ll reopen this issue and try to fix it ASAP.

**Comment by DSchumacher2104** [comment]
The clock seems to report a different voltage, because it usese 2 CR2032 Batteries. I think that's why Eve reports low battery. And the data update interval seems to be different, cause Eve shows a warning. But Temperature und Humidity Values work correct!

**Comment by hannseman** [comment]
@DSchumacher2104 thanks, I’ll have a look at these devices as soon as they are delivered. AliExpress to Sweden is not the fastest of processes :-)

**Comment by huongminh** [comment]
> Hi! Thanks for your kind words.
> 
> I have no idea if it will work but probably not. There's also a new OLED-version of the device that this plugin was written for: https://cleargrass.com/cg_temp_rh_monitor/overview
> 
> Hopefully I can get my hands on these two devices ASAP and with a little luck get it working.

Hi, This is really a great plugin! I tried your plugin with the new CLearGrass Version and it works out of the box with temp and humidity. Only the battery level is missing. Hope you will soon fix it.

**Comment by hannseman** [comment]
I've now been running both the new e-ink sensors for a couple of months without any issues expect for that the battery level is not updated.

I've tried to figure it out but it appears like the BLE advertisement package which contains the battery level is never sent. If one establishes a connection to the sensor the battery level can be read but this is not how this plugin is implemented.

Since the battery lasts very long on these devices and that they present the battery level on the screen I'm leaning against just adding an option to disable the battery level characteristic in homekit (ex `disableBatteryLevel`). This should remove all warnings in the Eve app.

I'll try and publish a version with this option ASAP.

**Comment by DJay-X** [comment]
@hannseman Will the new version be available at npm with disableBatteryLevel support? Thx.

**Comment by hannseman** [comment]
@DJay-X yes. I just want to test run it for couple of days first. I'll make a release on npm this week.

**Comment by hannseman** [comment]
I just published `2.3.0` to npm with the new option `disableBatteryLevel`. This should "fix" the only issue with the new E-Ink sensors. 

Closing this issue for now, feel free to request it to be reopened if any other issues are found. Thanks for all the reports in this issue!
