### ISSUE TITLE
Stuck on started scanning

### ISSUE THREAD

**Issue by JalilCejin** [hannseman/homebridge-mi-hygrothermograph#52]
Hi!

Running the latest version of the plugin and Homebridge using Mojave and a Mac with BLE.

I have already followed all the steps in the readme, including scanning for the identifier for the device. It shows 2 and tried with both in the address field on the config file.

Both devices show up on the Home app, but No Response is displayed.

The extended homebridge log shows the plugin 
- Start Scanning
- Started Scanning

and nothing else is shown regarding this plugin.

Could you please help?

Thanks

**Comment by hannseman** [comment]
Could you try running it with just one device active (remove the battery from one of them) and not specifying any address in the config. This is just to make sure that it’s just not the address ID that is wrong. Keep the sensor close to the device that is running homebridge.

Also could you please provide your homebridge config.

**Comment by JalilCejin** [comment]
Got it to work based on your suggestions.

I'm getting the address ID from nRF app on iOS, it shows 2 addresses. DFU and Primary service, tried both but no luck.

Any ideas?

`{
    "bridge": {
        "name": "BRCX1",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "777-88-777"
    },
    "platforms": [
        {
            "platform": "HarmonyHub",
            "name": "homebridge-harmonyhub-plugin"
        },
        {
            "platform": "config",
            "name": "Config",
            "port": 8081,
            "sudo": false,
            "log": {
                "method": "file",
                "path": "/users/jalil/.homebridge/logfile.log"
            }
        }
    ],
    "accessories": [
        {
            "accessory": "Hygrotermograph",
            "name": "Temperature & Humidity",
            "timeout": 15,
            "temperatureName": "Temperature",
            "humidityName": "Humidity",
            "fakeGatoEnabled": true
        }
    ]
}`

**Comment by hannseman** [comment]
I think the documentation is wrong about being able to use the nRF-app to retrieve the address/id you need. Each MacOS/iOS device will have its own unique identifier for each device that you need to use. On Linux systems you can use the MAC-address but this is on not available on Apple systems due to security reasons. 

Either you can try using Apples MacOS-app bluetooth explorer to find the UUID but for now the simplest saw might be to just run homebridge in debug-mode by `homebridge -D`. This will output more verbose logging about discovered sensors:

```
[2019-5-3 23:21:16] [Temperature & Humidity] [] Discovered peripheral
      Id: XXX
      LocalName: undefined
      rssi: -51
      serviceData: 5020....
```

```
[2019-5-3 23:21:16] [Temperature & Humidity] [] Discovered peripheral
      Id: YYY
      LocalName: undefined
      rssi: -51
      serviceData: 5020....
```

Look for entries where the field `Id` differ. Hopefully you'll only see 2 different Ids here (if you are using 2 sensors). Copy each Id into their respective `address` config. 

If you find an easier way to get the device UUID on MacOS please let me know. I actually started a project a while back to build a [command line tool](https://github.com/hannseman/blescan) which outputs the UUIDs in range on MacOS. Maybe I should try and finish it..

**Comment by JalilCejin** [comment]
OK, so I was able to find some new information.

- The UUID for the device is unique to the device and not to MacOS. I was able to scan the device with both the Mac and iPhone and both show the same UUID. So if you are able to get it from the iPhone, it would be the same on the Mac. 

- There are 2 service UUIDs, both are listed as Primary Service so still looking out for which one to use, tried with both but no luck.

- There is a way to get the mac address in MacOS. To achieve it you must be fast. Open bluetooth in System Information, then open bluetooth explorer, explore for BLE devices and when the sensor shows up, click on it and then on connect, as soon as you click on connect, switch to the System Information window and press Command-R as soon as bluetooth explorer shows some info. It will display the MAC address of the device. Will try to see if something happens using this MAC address.

**Comment by JalilCejin** [comment]
**Update 2: Good news**

Used the MAC address found in System Information/Bluetooth in the config file _**in lowercase**_ (uppercase didn't work) and voila, it's now reading the sensor correctly.

I never got it to work with the UUID (later, I discovered 4 more addresses for the same sensor, leading me to believe that each service has its own UUID. So If you are using MacOS, using the MAC address with the method provided above should do the trick.

**Comment by hannseman** [comment]
@JalilCejin good to hear! 

Weird that you had problems with uppercase not working, this is supposed to be handled: https://github.com/hannseman/homebridge-mi-hygrothermograph/blob/master/lib/scanner.js#L141-L150
