### ISSUE TITLE
Stopped scanning after RPi Update

### ISSUE THREAD

**Issue by kimme1024** [hannseman/homebridge-mi-hygrothermograph#57]
Hi!

I've been using this plugin for about a year now on an RPi and a Mac Mini which both have worked fine.

As I've encountered lot's of crashes on the RPi lately so I've updated it's firmware as well as the Raspbian distro I'm using.

Since then I've lost connection with my sensors connected to the RPi.

When starting homebridge I'm getting the following output:

[2019-6-6 11:05:34] [Slaapkamer] Initializing Hygrotermograph accessory...
[2019-6-6 11:05:34] [Badkamer] Initializing Hygrotermograph accessory...
[2019-6-6 11:05:34] [Fitness] Initializing Hygrotermograph accessory...
[2019-6-6 11:05:34] [Ikea Trådfri Gateway] didFinishLaunching
noble warning: adapter state unauthorized, please run as root or with sudo
               or see README for information on running without root/sudo:
               https://github.com/sandeepmistry/noble#running-on-linux
[2019-6-6 11:05:34] [Slaapkamer] Stop scanning. (unauthorized)
[2019-6-6 11:05:34] [Badkamer] Stop scanning. (unauthorized)
[2019-6-6 11:05:34] [Fitness] Stop scanning. (unauthorized)

I've updated node to the required version (8.6.0) and also tried to add "forceDiscovering" without success. Reinstalling the Bluetooth subsystem also didn't fix it.

It worked before the update so I guess something changed during the install of it but I have no clue what might have caused the issue.

### Versions
- **homebridge**: 
0.4.50

- **homebridge-mi-hygrothermograph**:
/usr/local/lib
└── homebridge-mi-hygrothermograph@2.2.1 

- **node**:
v8.6.0

- **OS**: 
Raspbian VERSION="9 (stretch)"

### Configuration
"accessories": [
        {
            "accessory": "Hygrotermograph",
            "name": "Slaapkamer",
            "address": "4C:65:A8:D7:94:03",
            "fakeGatoEnabled": "true",
            "forceDiscovering": "true"
        },
        {
            "accessory": "Hygrotermograph",
            "name": "Badkamer",
            "address": "4C:65:A8:D8:54:24",
            "fakeGatoEnabled": "true",
            "forceDiscovering": "true"
        },
        {
            "accessory": "Hygrotermograph",
            "name": "Fitness",
            "address": "4C:65:A8:DC:88:41",
            "fakeGatoEnabled": "true",
            "forceDiscovering": "true"
        }
    ],

I've seen other people having the same issue but always in a different situation that isn't applicable to my case. Let's hope someone can find a solution over here!

Thanks in advance!

**Comment by hannseman** [comment]
Hi! The error causing your sensors not to work is this one:
```
noble warning: adapter state unauthorized, please run as root or with sudo
or see README for information on running without root/sudo:
```

The issue is that node does not have permission to access Bluetooth. You either have to run it as root (not recommended) or follow the instructions linked in the README about running it as non-root:
 https://github.com/hannseman/homebridge-mi-hygrothermograph#install-homebridge-and-this-plugin
https://github.com/noble/noble#running-without-rootsudo

**Comment by kimme1024** [comment]
You're a hero!
I don't know why it suddenly changed it's behaviour but it works now! 

100x thank you!

**Comment by hannseman** [comment]
Haha no problem!
