### ISSUE TITLE
homebridge.err grows with bluetooth logs till sd card space is full

### ISSUE THREAD

**Issue by merdok** [hannseman/homebridge-mi-hygrothermograph#60]
Hi,

I have a problem with my homebridge since i installed this plugin. Around every two weeks my SD card on my raspberry pi runs full since the file `homebridge.err` gets like 25GB big with logs. All of the logs in the file are bluetooth scanning logs so i assume those come from you. Can you please disable the continuous logging?
This causes homebridge to crash and it will not start anymore again till i clean the disk..

**Comment by hannseman** [comment]
This plug-in should pretty much not log anything at all by default. You are most likely running with homebridge debug-mode enabled. Look if you are setting the `-D` flag when running homebridge or the `DEBUG=*` environment variable. Don’t run with debugging enabled and your disk space should be fine.

**Comment by merdok** [comment]
I am not running it in debug mode. The issue is the bluetooth logs. Those get constantly logged in `homebridge.err`, when i open the file then i see only bluetooth discovery messages. I suspect you log some information for yourself about the discovered devices but i guess unintentionally those logs somehow land in `homebridge.err`...

**Comment by hannseman** [comment]
You’re sure that the environment variable `DEBUG=*` is set? This will cause noble (library used for Bluetooth) to output _a lot_ of information.

Weird that it ends up in .err which I assume is the destination for stderr.. Could you please provide an example of the content that is logged?

**Comment by merdok** [comment]
Yes, i am pretty sure since this bluetooth log is the only thing which ends up in the file. Also this log only ends up in the file, in the console this log does not appear even when i run homebridge manually with the -D flag. 

Why it ends up in the .err file i do not know, but it is not an error log what is there.
The log is the standard hci discovery log. I can provide an example later when i have access to my Pi if needed. It basically shows discovered devices with service data.

**Comment by hannseman** [comment]
`DEBUG=*` is an environment variable and is not specific to homebridge. The bluetooth library is looking for this variable and if set it’ll spew out a lot of looks. Please have a look in your systemd files or how you are running homebridge if this is set.

**Comment by merdok** [comment]
You were right, i had the `DEBUG=*` variable set. I hope that fixes the issue. Thanks!
