### ISSUE TITLE
NOT AN ISSUE: After Market Bluetooth Adapter Mac OS

### ISSUE THREAD

**Issue by samsonrosen** [hannseman/homebridge-mi-hygrothermograph#61]
Hi! 

Just wanted to share that I am running a Macbook Pro Early 2011 which does not support BLE.

On a whim I bought this from Amazon which works perfectly with my Mac. I did remove the AirPort Card from the MacBook Pro (it's on ethernet anyway) to force it to use this device by default but it is working very well with this plugin. Thanks again!

https://www.amazon.co.uk/gp/product/B00LSGUBLI/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

**Comment by hannseman** [comment]
Hi! Thanks. Good to know that it's working fine on older Macbooks. I actually use the same adapter but on a Raspberry Pi 2.
