### ISSUE TITLE
turon off logging

### ISSUE THREAD

**Issue by muscaiu** [hannseman/homebridge-mi-hygrothermograph#62]
Is there any way to turn off logging ?
It's so much noise in the console and i can't read anything.

```
[4c:65:a8:dd:7f:c9] Discovered peripheral
      Id: 4c65a8dd7fc9
      LocalName: MJ_HT_V1
      rssi: 0
      serviceData: 5020aa018dc97fdda8654c0d100421017702
[4c:65:a8:dd:7f:c9] Discovered peripheral
      Id: 4c65a8dd7fc9
      LocalName: MJ_HT_V1
      rssi: -85
      serviceData: 5020aa018ec97fdda8654c0410022101
[4c:65:a8:dd:7f:c9] Discovered peripheral
      Id: 4c65a8dd7fc9
      LocalName: MJ_HT_V1
      rssi: -84
      serviceData: 5020aa018fc97fdda8654c0d100422017702
[4c:65:a8:dd:7f:c9] Discovered peripheral
      Id: 4c65a8dd7fc9
      LocalName: MJ_HT_V1
      rssi: -79
      serviceData: 5020aa0191c97fdda8654c0d100423017702
.....
```

**Comment by hannseman** [comment]
I guess that you are not running this plugin through homebridge as discussed in another issue. When running through homebridge and not setting the `-D` flag to enable debug mode the logging is minimal. If you read the code you can see that you can pass a custom logging object to `Scanner` like this `new Scanner(address, {'log': console})`. Switch out console to something else that follows the [Console API](https://nodejs.org/api/console.html).

For example something like this:
`const log = { debug() {}, error() {}, warn() {}, info() {} };`

This will silence all logging-calls. To just disable `.debug` you could add `console.log` to all others.

Closing this issue as it's not really related to this homebridge plugin.

**Comment by muscaiu** [comment]
I tried this,
```
const kitchenId = '4c65a8dd7c37';
const kitchenScanner = new Scanner(kitchenId, { log });
const log = { debug() { }, error() { }, warn() { }, info() { } };
```
I tried `const kitchenScanner = new Scanner(kitchenId, { log: null });` or empty object, but it will not shut it up.

What code should i read?

**Comment by hannseman** [comment]
Uhm you're defining `log` after instantiating the `Scanner`. So the `{ log }` your passing will just be undefined and thus default to console. Should look like this
```js
const kitchenId = '4c65a8dd7c37';
const log = { debug() { }, error() { }, warn() { }, info() { } };
const kitchenScanner = new Scanner(kitchenId, { log });
```

**Comment by muscaiu** [comment]
@hannseman tou're right! Thanks again for the quick help!
