### ISSUE TITLE
Camibration Option 

### ISSUE THREAD

**Issue by ripcurl7777** [hannseman/homebridge-mi-hygrothermograph#63]
### Expected Behavior

Make an Option to calibrate the Temp and humidity to have an Offset like Meausred 53% real 51% so offset is -2 Same for temp.
Cause this Devices are Not accurate

### Versions

- **homebridge**: `homebridge --version`
- **homebridge-mi-hygrothermograph**: `npm list --depth 1 --global homebridge-mi-hygrothermograph`
- **node**:       `node --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by hannseman** [comment]
Thanks for your report. Have you observed this inaccuracy on multiple devices, i.e maybe you got a bad sensor?

**Comment by ripcurl7777** [comment]
Hi,

I habe 6 of them and all are off in either negative or positive compared to a calibrated hygro / temp meter 

Von meinem iPhone gesendet

**Comment by hannseman** [comment]
Okay, good to know. I'll try and add a `temperatureOffset`and `humidityOffset` option ASAP.

**Comment by ripcurl7777** [comment]
Thanks a lot and habe a nice day.
 

 
 

Gesendet: Sonntag, 11. August 2019 um 23:52 Uhr
Von: "Hannes Ljungberg" <notifications@github.com>
An: hannseman/homebridge-mi-hygrothermograph <homebridge-mi-hygrothermograph@noreply.github.com>
Cc: ripcurl7777 <martinkropf@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [hannseman/homebridge-mi-hygrothermograph] Camibration Option (#63)


Okay, good to know. I'll try and add a temperatureOffsetand humidityOffset option ASAP.

**Comment by hannseman** [comment]
I just published v2.3.0 to npm which have the new options `temperatureOffset` and `humidityOffset`.

Thanks for your feature request.
