### ISSUE TITLE
Expand the config-sample.json file to include a working example of an MQTT broker

### ISSUE THREAD

**Issue by gitnubee** [hannseman/homebridge-mi-hygrothermograph#64]
**Expected Behavior**
Expand on the config-sample.json file to include a working example of an MQTT broker that is NOT test.mosquitto.org so that newbies like myself can copy the example provided. 
For example what config would I need to send MQTT messages to a server at 192.168.0.2??

Also, the MQTT section where is it supposed to appear within the config.json file?

Is it under platforms? accessories? somewhere else?
At present I have placed it in the platforms section but it doesn't work. :(

**Current Behavior**

**Steps to Reproduce (for bugs)**

**Versions**

**Configuration**
My current config.json is below the temperature and humidity are being displayed BUT the mqtt data is not:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CB:22:3D:E2:CE:31",
        "port": 51826,
        "pin": "033-44-254"
    },
    "accessories": [
        {
            "accessory": "Hygrotermograph",
            "name": "Main Hall",
            "address": "4C:65:A8:xx:xx:xx",
            "timeout": 15,
            "temperatureName": "Temperature",
            "humidityName": "Humidity",
            "fakeGatoEnabled": false
        }
    ],
    "platforms": [
        {
    "mqtt": {
    "url": "mqtt://test.mosquitto.org",
    "temperatureTopic": "sensors/temperature",
    "humidityTopic": "sensors/humidity",
    "batteryTopic": "sensors/battery"
  },

		  "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "teal",
            "restart": "sudo -n systemctl restart homebridge",
            "tempUnits": "c",
            "sudo": true,
            "log": {
                "method": "systemd"
            },
            "platform": "config"
        }
    ]
}

**Comment by DSchumacher2104** [comment]
I Think you have to put the MQTT section into each accessory, in your example after "fakeGatoEnabled": false. It did it so and the plugin connected to my broker. However, i couldn't see any topic or data on the broker yet :-(

**Comment by gitnubee** [comment]
Thanks DSchumacher2104, for the hint. I now have it working.
My working config is below which should make it easy for someone else to copy and use in future.

{  
   "bridge":{  
      "name":"Homebridge",
      "username":"CB:22:3D:E2:CE:31",
      "port":51826,
      "pin":"033-44-254"
   },
   "accessories":[  
      {  
         "accessory":"Hygrotermograph",
         "name":"Main Hall",
         "address":"4C:65:A8:XX:XX:XX",
         "timeout":15,
         "temperatureName":"Temperature",
         "humidityName":"Humidity",
         "fakeGatoEnabled":false,
         "mqtt":{  
            "url":"mqtt://192.168.0.2",
            "temperatureTopic":"sensors/temperature",
            "humidityTopic":"sensors/humidity",
            "batteryTopic":"sensors/battery"
         }
      }
   ],
   "platforms":[  
      {  
         "name":"Config",
         "port":8080,
         "auth":"form",
         "theme":"teal",
         "restart":"sudo -n systemctl restart homebridge",
         "tempUnits":"c",
         "sudo":true,
         "log":{  
            "method":"systemd"
         },
         "platform":"config"
      }
   ]
}
