### ISSUE TITLE
ClearGrass (2019) E-Ink Temperature and Humidity - Battery Issue

### ISSUE THREAD

**Issue by DJay-X** [hannseman/homebridge-mi-hygrothermograph#65]
@hannseman First of all thanks for your great work, the time you are investing and for sharing your plugin.

I was using the plugin successfully with one Xiaomi Mi Bluetooth Temperature and Humidity Sensor on my Pi Zero W for a few weeks now.
Now I bought two new Model of the ClearGrass Sensor with E-Ink Display. http://bit.ly/2yMsMMv

They also show up in HomeKit/Eve App but unfortunately always with an error of low battery. Am I doing something wrong or is there no full support at the moment for the new ClearGrass E-Ink Sensors? I should have checked earlier. 😅 Probably related to https://github.com/hannseman/homebridge-mi-hygrothermograph/issues/50

Hope you can help and again, thanks for your time and support.
If there is anything I can do to help, please of course let me know.

![Napkin 2 10 08 19, 8 07 34 PM](https://user-images.githubusercontent.com/3874239/62825351-8911f280-bbaa-11e9-9157-d3b9f1ef2679.png)

```
{
            "accessory": "Hygrotermograph",
            "name": "Raumklima",
            "address": "58:2d:34:31:07:f8",
            "timeout": 15,
            "lowBattery": 15,
            "temperatureName": "Temperatur",
            "humidityName": "Luftfeuchtigkeit",
            "fakeGatoEnabled": true,
            "fakeGatoStoragePath": "/var/homebridge/"
        },
        {
            "accessory": "Hygrotermograph",
            "name": "Raumklima Esszimmer",
            "address": "58:2d:34:10:49:9c",
            "timeout": 15,
            "lowBattery": 15,
            "temperatureName": "Temperatur",
            "humidityName": "Luftfeuchtigkeit",
            "fakeGatoEnabled": true,
            "fakeGatoStoragePath": "/var/homebridge/"
        },
        {
            "accessory": "Hygrotermograph",
            "name": "Raumklima Schlafzimmer",
            "address": "58:2d:34:10:48:f3",
            "timeout": 15,
            "lowBattery": 15,
            "temperatureName": "Temperatur",
            "humidityName": "Luftfeuchtigkeit",
            "fakeGatoEnabled": true,
            "fakeGatoStoragePath": "/var/homebridge/"
        }
```

**Comment by hannseman** [comment]
Thanks for you kind words!

Yes battery status is not supported on the new e-ink sensors. I've tried to figure it out but it appears like they simply do not advertise the battery level in the bluetooth advertisement packages. To read the battery level one has to establish as connection to the sensor and this is not how this plugin is implemented.

My suggestion to get rid of the warning is to add an option (ex `disableBatteryLevel`) to not tell homekit that this sensor presents a battery level. I'll try and publish a new version with this option ASAP.

I'm closing this issue in favour of #50

**Comment by huongminh** [comment]
The new firmware now supports battery. Thank you for your great plugin

**Comment by hannseman** [comment]
@huongminh good to know. Thanks!
