### ISSUE TITLE
Temperature to file

### ISSUE THREAD

**Issue by alexls74** [hannseman/homebridge-mi-hygrothermograph#72]
Hi,
Could you add the option to record the current temperature to a text file?

**Comment by hannseman** [comment]
Hi! You could use MQTT to achieve that. 
* Set up an MQTT broker and publish the temperature topic to it. See the README for more information on how to configure this plugin against an MQTT broker: https://github.com/hannseman/homebridge-mi-hygrothermograph#mqtt
* Write a script to run as a daemon that subscribes to the temperature topic and writes to a text file.

Good luck!
