### ISSUE TITLE
Fakegato History not supported anymore after update Eve App v3.8.1

### ISSUE THREAD

**Issue by DJay-X** [hannseman/homebridge-mi-hygrothermograph#73]
After updating to latest Eve App v3.8.1 all my Devices via homebridge-mi-hygrothermograph doesn't show any History at all anymore.
There is literally no option/graph for History anymore.
Of course in my config nothing has changed. 

{
            "accessory": "Hygrotermograph",
            "name": "Raumklima",
            "address": "58:2d:34:31:07:f8",
            "timeout": 30,
            "updateInterval": 300,
            "lowBattery": 15,
            "temperatureName": "Temperatur",
            "humidityName": "Luftfeuchtigkeit",
            "fakeGatoEnabled": true,
            "disableBatteryLevel": true,
            "fakeGatoStoragePath": "/var/homebridge/"
        },

With other plugins that use also fakegato, the history is still available and showing up.

Does you @hannseman or anybody else also facing this issue?

![Napkin 2 28 08 19, 4 16 52 PM](https://user-images.githubusercontent.com/3874239/63863916-44aa9300-c9af-11e9-8a2f-7c39f000d7bf.png)

**Comment by dimm72** [comment]
the same problem

**Comment by hannseman** [comment]
Looks like something that needs to be fixed in fakegato-history. See this issue https://github.com/simont77/fakegato-history/issues/76

**Comment by mrdc** [comment]
In my case homebridge-mi-hygrothermograph is not saving any history - "fakeGatoEnabled" is set to true, but "fakegato-history_HygrothermographAccessory.json" has only a few records in it and no new data was added to it since May 2019.

**Comment by martano12** [comment]
Aqara thermometers directly attached to Homekit via Aqara hub does not show history too.
Weather plus neither

**Comment by DJay-X** [comment]
With recent Eve App Update v3.8.3, the history graph is back!

**Comment by hannseman** [comment]
Awesome! 🎉
