### ISSUE TITLE
Current temperature File

### ISSUE THREAD

**Issue by magnificent3** [hannseman/homebridge-mi-hygrothermograph#78]
Is it possible to get a current temperature file so it can be read by another accessory?
It's like the fakegato but only with the current temperature for each device.

**Comment by hannseman** [comment]
Hi! You could use MQTT to achieve that.

Set up an MQTT broker and publish the temperature topic to it. See the README for more information on how to configure this plugin against an MQTT broker: https://github.com/hannseman/homebridge-mi-hygrothermograph#mqtt
Write a script to run as a daemon that subscribes to the temperature topic and writes to a text file.

Good luck!
