### ISSUE TITLE
Support for Other Sensors

### ISSUE THREAD

**Issue by CaptBeard** [hannseman/homebridge-mi-hygrothermograph#87]
Is there a way I can modify your scanner to support other BLE sensors?
Specifically I'm trying to use a "Govee_H5074_E893"
With your package, I'm unable to pull anything as it says "accessory not responding".
My guess is your specifically targeting a Mi sensor.

**Comment by hannseman** [comment]
It depends on how that sensor is implemented. The Mi sensor emits the sensor data in the BLE advertisement packages and that not require a connection between the system running homebridge and the sensor, i.e the reading is passive. If the Govee sensor works the same way it's "just" a matter of reverse engineering the data sent in the advertisement packages and replace the implenentation in this package with the Govee one. The Mi implementation of this is made in https://github.com/hannseman/homebridge-mi-hygrothermograph/blob/master/lib/parser.js.

Good luck!
