### ISSUE TITLE
HomeKit displays temp and humidity, but unable to create automation 

### ISSUE THREAD

**Issue by willio** [hannseman/homebridge-mi-hygrothermograph#88]
I run the device as is and use the plugin to let Homebridge detects it without the Mijia Gateway. 

Is it a limitation of HomeKit or am I assuming wrong that the plugin would act as a bridge and use the data from the sensor to create automation chain?

**Comment by hannseman** [comment]
I'm not really sure what you mean but Homekit does not natively support automations on temperature / humidity. You can use thirdparty apps to solve this. Shortcuts can also be used, see https://github.com/hannseman/homebridge-mi-hygrothermograph#automation-ios-13.
