### ISSUE TITLE
Error: Cannot find module '../build/Release/binding.node'

### ISSUE THREAD

**Issue by qzlsdb** [hannseman/homebridge-mi-hygrothermograph#9]
I'm encountering an err message as below:

Error: Cannot find module '../build/Release/binding.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-bluetooth/node_modules/bluetooth-hci-socket/lib/native.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

And when I uninstall the homebridge-mi-hygrothermograph plug-in the error was fixed.

**Comment by hannseman** [comment]
What platform are you on and what Node version are you running? Have you followed the installation instructions? If you’re on a Debian based system you need to run `sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev` before running `npm install -g homebridge-mi-hygrothermograph`.

**Comment by BeLove** [comment]
I guess platform is ARM and topic starter is trying to use it on raspberry pi.

**Comment by qzlsdb** [comment]
I tried the system of OSMC and Raspbian Stretch Lite on a Raspberry Pi B model,  they all take me the same err messages as above. I already intall "sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev".

**Comment by hannseman** [comment]
Weird! Do you see any errors during the installation process? What version of node are you running? `node -v`

**Comment by hannseman** [comment]
If you see any errors you could try`npm install -g --unsafe-perms homebridge-mi-hygrothermograph`.

**Comment by hannseman** [comment]
Hmm. Just looked a bit closer at your error message and the crash appears to happen in the [homebridge-bluetooth](https://github.com/vojtamolda/homebridge-bluetooth) and not in this plugin. Very weird that this plugin would be causing that one to crash. Try uninstalling that plugin and install this one again and see if it works. Then try to install homebridge-bluetooth again and see if the issue reappears.

**Comment by qzlsdb** [comment]
YEAH! I already fixed the problem by the "npm install -g --unsafe-perms homebridge-mi-hygrothermograph", thank you very much. 
Moreover, the commonder "sudo apt-get install libcap2-bin" and "sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)" need to run first, when the system show the err message "the noble is stopped scaning"

**Comment by George88JL** [comment]
Hi, can you help me? I try on RPi3

pi@raspberrypi:~ $ node -v
v8.11.1

pi@raspberrypi:~ $ sudo npm install -g --unsafe-perms homebridge-mi-hygrothermograph
+ homebridge-mi-hygrothermograph@1.4.0
updated 1 package in 19.099s

pi@raspberrypi:~ $ sudo hcitool lescan
LE Scan ...
4C:65:A8:D1:E9:28 (unknown)
4C:65:A8:D1:E9:28 MJ_HT_V1
4C:65:A8:D2:04:C7 (unknown)
4C:65:A8:D2:04:C7 MJ_HT_V1

**Add accesory to config.json**


	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

	"accessories": [{
			"accessory": "PiTemperature",
			"name": "Raspberry PI Temperature"
		},
		{
			"accessory": "Hygrotermograph",
			"name": "Room 1",
			"address": "4C:65:A8:D1:E9:28"
		},
		{
			"accessory": "Hygrotermograph",
			"name": "Room 2",
			"address": "4C:65:A8:D2:04:C7"
		}



pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-4-9 20:10:01] Plugin /usr/lib/node_modules/homebridge-bluetooth does not contain a package.json.
[2018-4-9 20:10:01] Loaded plugin: homebridge-mi-hygrothermograph
module.js:549
    throw err;
    ^

Error: Cannot find module '../build/Release/binding.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/bluetooth-hci-socket/lib/native.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)


**after i uninstall homebridge-mi-hygrothermograph and edit config.json file, works homebridge fine.**

pi@raspberrypi:~ $ sudo npm uninstall -g --unsafe-perms homebridge-mi-hygrothermograph
removed 119 packages in 8.983s

pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-4-9 20:06:23] Plugin /usr/lib/node_modules/homebridge-bluetooth does not contain a package.json.
[2018-4-9 20:06:23] Plugin /usr/lib/node_modules/homebridge-mi-hygrothermograph does not contain a package.json.
[2018-4-9 20:06:23] Loaded plugin: homebridge-pi
[2018-4-9 20:06:23] Registering accessory 'homebridge-pi.PiTemperature'
[2018-4-9 20:06:23] ---
[2018-4-9 20:06:23] Loaded config.json with 1 accessories and 0 platforms.
[2018-4-9 20:06:23] ---
[2018-4-9 20:06:23] Loading 1 accessories...
[2018-4-9 20:06:23] [Raspberry PI Temperature] Initializing PiTemperature accessory...
[2018-4-9 20:06:23] [Raspberry PI Temperature] Model BCM2835/a02082 Serial 00000000f99a26c9
Setup Payload:


Im fresh starter coder with homebridge, thank you for your help. 

Do I need Xiaomi Gateway ? I dont have it.

**Comment by George88JL** [comment]
Thank you, after un/install --unsafe... work like a charm. Thank you for your help.

**Comment by yesimxev** [comment]
The above methods did not work for me. For anyone who needs another solution. Looks like the bindings.node can be just simply pasted where the program looks for it. Eg. use `strace YOUR_COMMAND` and check which folder is it being searching in.
Then 
```
git clone https://github.com/noble/node-bluetooth-hci-socket.git
mkdir -p /root/YOUR_PROGRAM/node_modules/noble/node_modules/bluetooth-hci-socket/build/Release
cp /root/node-bluetooth-hci-socket/build/Release/binding.node /root/YOUR_PROGRAM/node_modules/noble/node_modules/bluetooth-hci-socket/build/Release/
```

**Comment by Jacek951007** [comment]
> The above methods did not work for me. For anyone who needs another solution. Looks like the bindings.node can be just simply pasted where the program looks for it. Eg. use `strace YOUR_COMMAND` and check which folder is it being searching in.
> Then
> 
> ```
> git clone https://github.com/noble/node-bluetooth-hci-socket.git
> mkdir -p /root/YOUR_PROGRAM/node_modules/noble/node_modules/bluetooth-hci-socket/build/Release
> cp /root/node-bluetooth-hci-socket/build/Release/binding.node /root/YOUR_PROGRAM/node_modules/noble/node_modules/bluetooth-hci-socket/build/Release/
> ```

I just used my paths, and it works two times for me. Thank you :+1:
