### ISSUE TITLE
New update for E-INK sensor and battery

### ISSUE THREAD

**Issue by Vannixxo** [hannseman/homebridge-mi-hygrothermograph#91]
Hello, I’ve read that one user successfully updated the new version of the sensor and now the battery packet is broadcasted too!

Can anyone else confirm this? Which app to update it? Mi home or ?
Thanks!

**Comment by hannseman** [comment]
@huongminh reported this in https://github.com/hannseman/homebridge-mi-hygrothermograph/issues/65#issuecomment-559853198. I haven't gotten around to actually upgrade my clock sensor. 

And yes you would use the Mi home app to upgrade the sensor.
