### ISSUE TITLE
Dependencies install error inside Docker on RPI

### ISSUE THREAD

**Issue by Vannixxo** [hannseman/homebridge-mi-hygrothermograph#92]
Hello, I'm trying to install and use this plugin inside docker on RPI, with both bash and sh inside docker, I get install errors for "sudo apk add bluetooth bluez libbluetooth-dev libudev-dev"

ERROR: unsatisfiable constraints:
  bluetooth (missing):
    required by: world[bluetooth]
  libbluetooth-dev (missing):
    required by: world[libbluetooth-dev]
  libudev-dev (missing):
    required by: world[libudev-dev]

I think It is related to Alpine?

Also, I tried to install the plugin and then remove it, but I still get this error from homebridge console:

[1/24/2020, 9:35:24 PM] [Config] Failed to parse plugin "homebridge-mi-hygrothermograph": ENOENT: no such file or directory, open '/homebridge/node_modules/homebridge-mi-hygrothermograph/package.json'

**Comment by hannseman** [comment]
Hi, yes you need to find the corresponding packages for alpine. You'll also atleast need to use `--cap-add=NET_RAW` to give the container access to bluetooth.

> Also, I tried to install the plugin and then remove it, but I still get this error from homebridge console:
[1/24/2020, 9:35:24 PM] [Config] Failed to parse plugin "homebridge-mi-hygrothermograph": ENOENT: no such file or directory, open '/homebridge/node_modules/homebridge-mi-hygrothermograph/package.json'

No idea, make sure that you've removed it from your homebridge config-file.

Good luck!

**Comment by Vannixxo** [comment]
Really don’t know, I’ve of course deleted everything from the config file, this is strange..

For the BT access I was ready to go with:

sudo apk add bluetooth bluez libbluetooth-dev libudev-dev 

and 

run sudo setcap cap_net_raw+eip $(eval readlink -f `which node`) 

But at this point I need to find a way to install the packages first

**Comment by hannseman** [comment]
When you’ve managed to install the dependencies you might want to take a look at https://github.com/hannseman/homebridge-mi-hygrothermograph/issues/48

**Comment by Vannixxo** [comment]
> When you’ve managed to install the dependencies you might want to take a look at #48

Yes thanks! I already seen that post, in the meanwhile I successfully run the second command to expose BT control, but as the docker container is based on alpine, I only found bluez package and nothing else... plus, I always get some errors when installing your plugin but can’t find homebridge.err log to retrieve the issues, I only find the regular log file unfortunately
