### ISSUE TITLE
Bluetooth: hci0 advertising data length corrected

### ISSUE THREAD

**Issue by tomky** [hannseman/homebridge-mi-hygrothermograph#98]
After I installed this plugin on my RP3, the system log shows the following errors repeatedly in a crazy speed, which seems a bad thing so I removed it right away:

`Bluetooth: hci0 advertising data length corrected`

It seems this is caused by Bluetooth overload, which I assume is caused by continuous BLE scanning. I wonder if this can be solved by reducing the scanning rate, and if so how? BTW, adjusting updateInterval doesn’t help.

**Comment by hannseman** [comment]
I can't see why this would be caused by scanning for BLE devices. A quick googling suggests that people see this error due to using an under-dimensioned power supply. I would recommend trying a 3A power supply.

**Comment by tomky** [comment]
That is what I originally suspect. Nevertheless, I tried the official RP power supply and other 3A+ power supply and no luck so far.

In the error messages I can see that the error happens so often that it is even suppressed by the system, which I believe is caused by the scanning as no other BE applications I used cause the same error.

**Comment by hannseman** [comment]
Did you ever manage to track down this issue?

**Comment by tomky** [comment]
I tried to edit the scanning speed in noble package directly. In general, when the scanning speed is reduced, the error happens much less frequently. Unfortunately, the devices cannot be found if I change the scanning speed, which makes this trick useless.

**Comment by vbarba** [comment]
Same message here with a RP3.
