### ISSUE TITLE
No response in Homekit app after updating nodejs

### ISSUE THREAD

**Issue by SSkull995** [hannseman/homebridge-mi-hygrothermograph#99]
Hi all! 

I just updated node to the latest version in my raspi4 with homebridge, and I don't know why my hygro does not work anymore. I noticed I had some errors in the log due to the old version of the plugin, so I updated it and now there is no more error in the log of homebridge. However, when I look in the HomeKit app, the two sensors are in "no response" state. 
I tried also with "sudo hcitool lescan" and the device is found, with also the address, which I included in the json file, with no luck. 

Anyone knows how I can overcome this problem? Thank you!

**Comment by hannseman** [comment]
If you’re not running node as root you need to give node access to bluetooth:
```
sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)
```

Also make sure that you’ve reinstalled this plugin.

**Comment by SSkull995** [comment]
Hi! I just ran the string you posted, now it works! Many thanks! I couldn’t find anything like this for this situation.
